// utils/constants.js
import { 
  Globe, Users, BookOpen, Target, Award, Languages,
  FileText, BarChart, Map, Shield, Cpu, Database,
  GitBranch, Cloud, Server, Terminal, Lock, Code,
  Linkedin, Twitter, Github, Mail, Phone, MapPin,
  Calendar, Briefcase, ExternalLink, Download,
  GraduationCap, Building, Search, Brain, Mic,
  Book, PieChart, UserCheck, Settings
} from 'lucide-react';

export const navLinks = [
  { name: 'Home', href: '#home' },
  { name: 'About', href: '#about' },
  { name: 'Experience', href: '#experience' },
  { name: 'Education', href: '#education' }, // Add this
  { name: 'Projects', href: '#projects' },
  { name: 'Publications', href: '#publications' },
  { name: 'Contact', href: '#contact' },
];

export const heroData = {
  name: 'Dr. Michael Sitawa Mugah',
  title: 'Senior Researcher & Strategic Consultant',
  bio: 'Ph.D in Sociology with extensive experience in Security Sector Reform, Peace Operations, and Maritime Security in Eastern Africa.',
  stats: [
    { value: '15+', label: 'Years Experience' },
    { value: '50+', label: 'Research Projects' },
    { value: '30+', label: 'Publications' },
    { value: '100+', label: 'Students Supervised' },
  ],
};

export const aboutData = {
  bio: 'Driven by a passion for strategic management, market surveillance, networking, resource mobilization, research and publication, I have extensive experience in strategic planning, negotiation, conflict resolution, management, research, monitoring and evaluation, data collection, data analysis, presentation, and report writing.',
  stats: [
    { value: 'Ph.D', label: 'Sociology, Kenyatta University' },
    { value: 'M.A', label: 'Community Development, UoN' },
    { value: 'B.A', label: 'Social Sciences, CUEA' },
  ],
  competencies: [
    'Strategic Planning',
    'Security Sector Reform',
    'Peace Operations',
    'Maritime Security',
    'Conflict Resolution',
    'Policy Development',
    'Research Methodology',
    'Capacity Building',
    'Data Analysis',
    'Public Speaking',
  ],
  languages: [
    { name: 'English', level: 'Native', proficiency: 100 },
    { name: 'French', level: 'Fluent', proficiency: 90 },
    { name: 'Kiswahili', level: 'Native', proficiency: 100 },
  ],
};

export const skills = [
  { name: 'Strategic Planning', level: 'Expert', icon: <Target /> },
  { name: 'Research Methodology', level: 'Expert', icon: <BookOpen /> },
  { name: 'Data Analysis (SPSS)', level: 'Expert', icon: <BarChart /> },
  { name: 'Policy Analysis', level: 'Expert', icon: <FileText /> },
  { name: 'Conflict Resolution', level: 'Expert', icon: <Shield /> },
  { name: 'Project Management', level: 'Expert', icon: <Users /> },
  { name: 'Public Speaking', level: 'Expert', icon: <Mic /> },
  { name: 'Academic Writing', level: 'Expert', icon: <Book /> },
  { name: 'Stakeholder Engagement', level: 'Expert', icon: <UserCheck /> },
  { name: 'Resource Mobilization', level: 'Advanced', icon: <Settings /> },
];

export const experienceCategories = [
  { id: 'all', label: 'All Experience', icon: <Briefcase /> },
  { id: 'research', label: 'Research', icon: <Search /> },
  { id: 'academic', label: 'Academic', icon: <GraduationCap /> },
  { id: 'consulting', label: 'Consulting', icon: <Building /> },
  { id: 'administration', label: 'Administration', icon: <Settings /> },
];

export const experiences = [
  // CURRENT ROLES
  {
    id: 1,
    position: 'Researcher',
    company: 'Institute for Security Studies',
    period: 'Aug 2024 - Present',
    location: 'Nairobi, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Conduct desktop research and contribute to security sector governance projects in Eastern Africa.',
    responsibilities: [
      'Conduct desktop research to gather and synthesise existing information on relevant topics',
      'Assist in mapping and analysing academic and policy literature for Security Sector Reform',
      'Contribute to survey design tailored to research project objectives',
      'Analyse research findings using appropriate methodologies',
      'Prepare research reports and presentations for stakeholders',
      'Participate in dissemination workshops and seminars',
    ],
    achievements: [
      'Mapping of civil society organizations in security sector governance space in Eastern Africa',
      'Mapping of key stakeholders for engagement in Nairobi',
      'Report writing for civil society organizations project covering Eastern African region',
      'Organized Kenya Stakeholder Engagements in Nairobi',
    ],
    skills: ['Security Sector Reform', 'Policy Analysis', 'Stakeholder Mapping', 'Report Writing', 'Data Collection'],
  },
  {
    id: 2,
    position: 'Senior Researcher',
    company: 'International Peace Support Training Centre',
    period: 'May 2020 - Present',
    location: 'Karen, Nairobi',
    type: 'Research',
    category: 'research',
    description: 'Conducting evidence-based research on gender, peace and security issues in Eastern Africa region.',
    responsibilities: [
      'Conduct demand-led, evidence-based policy-oriented research',
      'Analyse gendered nature of emerging conflict trends in Eastern Africa',
      'Provide inputs for training related to peace operations',
      'Develop and utilize appropriate research methodologies',
      'Prepare background notes, briefings, and speeches for Senior Management',
      'Lead high-profile research activities and support colleagues',
    ],
    achievements: [
      'Secured $54,000 USD funding for Children, Peace and Security research conference',
      'Established international collaborations with 8+ institutions through MoUs',
      'Published 5+ research papers and books',
      'Constituted international review board for Africa Amani Journal',
      'Designed and implemented Centre visibility strategy',
    ],
    projects: [
      'Disaster Risk Reduction in Conflict Zones',
      'SDG 5 in Maritime Security',
      'Multi-agency coordination in IED Threat Mitigation',
    ],
    skills: ['Peace Operations', 'Gender Analysis', 'Research Design', 'Fundraising', 'International Collaboration'],
  },
  {
    id: 3,
    position: 'Interim Programme Head',
    company: 'National Defence University-Kenya',
    period: 'Dec 2021 - Present',
    location: 'Karen, Nairobi',
    type: 'Academic Leadership',
    category: 'academic',
    description: 'Lead the Master of Arts Programme in National Security and Strategy.',
    responsibilities: [
      'Academic and administrative head of the MA programme',
      'Chair regular departmental meetings and ensure policy implementation',
      'Represent programme on appropriate college committees',
      'Maintain proper standards of teaching and research',
      'Submit departmental budgets, procurement plans, and annual reports',
      'Provide performance reviews of academic and non-academic staff',
    ],
    achievements: [
      'Drafted Student Recruitment, Resource Mobilization, Scholarship policies',
      'Enhanced programme coordination between College and University',
      'Improved academic and administrative standards',
    ],
    skills: ['Academic Leadership', 'Program Management', 'Quality Assurance', 'Strategic Planning', 'Policy Development'],
  },

  // ACADEMIC & TEACHING ROLES
  {
    id: 4,
    position: 'Provision of Instructional Assistance',
    company: 'Defence Staff College',
    period: 'Jan 2021 - Present',
    location: 'Karen, Nairobi',
    type: 'Teaching',
    category: 'academic',
    description: 'Prepare and deliver lectures for Grade 3 Course Participants preparing for promotion.',
    responsibilities: [
      'Prepare lecture materials for promotion courses',
      'Deliver lectures on Conflict Resolution and Management in Africa',
      'Teach courses on Africa Peace and Security Architecture',
      'Instruct on United Nations Organization structures and operations',
    ],
    skills: ['Military Education', 'Curriculum Development', 'Adult Learning', 'Security Studies'],
  },
  {
    id: 5,
    position: 'Senior Lecturer',
    company: 'Catholic University of Eastern Africa',
    period: 'Jan 2010 - Apr 2021',
    location: 'Langata and Kisumu, Kenya',
    type: 'Teaching',
    category: 'academic',
    description: 'Lectured across multiple departments and supervised student research.',
    responsibilities: [
      'Coordinated examinations timetables for Social Sciences department',
      'Researched and prepared book lists for Masters programmes',
      'Supervised research concepts and projects by students',
      'Prepared and delivered lectures for undergraduate and graduate courses',
      'Examined, invigilated, and marked examinations',
      'Participated in departmental meetings and curriculum review',
    ],
    courses: [
      'Community Development',
      'Sociology of Development',
      'Research Methods',
      'Social Theory',
      'Human Rights',
      'Natural Resources Management',
    ],
    achievements: [
      'Supervised 50+ Masters and undergraduate theses',
      'Spearheaded Faculty curriculum review across five departments',
      'Wrote Diploma programmes for the department',
    ],
    skills: ['Curriculum Development', 'Thesis Supervision', 'Course Design', 'Academic Assessment', 'Departmental Leadership'],
  },
  {
    id: 6,
    position: 'Part-time Lecturer',
    company: 'Kisii University',
    period: 'Jan 2015 - Present',
    location: 'Nairobi Campus',
    type: 'Teaching',
    category: 'academic',
    description: 'Teach Masters courses in Development Studies, Public Administration, and International Relations.',
    responsibilities: [
      'Prepare lecture materials for Masters courses',
      'Deliver lectures on Change and Development',
      'Teach Public Administration in Kenya',
      'Instruct on Politics and Development of Newly Industrialized Countries',
      'Examine and mark student assessments',
    ],
    skills: ['Graduate Teaching', 'International Relations', 'Public Administration', 'Development Studies'],
  },
  {
    id: 7,
    position: 'Part-time Lecturer',
    company: 'Chuka University',
    period: 'Jan 2014 - Apr 2015',
    location: 'Chuka, Kenya',
    type: 'Teaching',
    category: 'academic',
    description: 'Taught undergraduate courses in Sociology and Social Work.',
    responsibilities: [
      'Prepared lecture materials for Sociology courses',
      'Delivered lectures on Social Policy, Research Methods, and Rural Sociology',
      'Taught courses on Correctional Services and Social Stratification',
      'Examined and marked student assessments',
    ],
    skills: ['Sociology Instruction', 'Social Work Education', 'Undergraduate Teaching'],
  },
  {
    id: 8,
    position: 'Part-time Lecturer',
    company: 'Maseno University',
    period: 'May - Aug 2012',
    location: 'Kisumu, Kenya',
    type: 'Teaching',
    category: 'academic',
    description: 'Taught courses on Ethnicity, Nationalism, and Anthropology of Poverty.',
    responsibilities: [
      'Prepared lecture materials for assigned courses',
      'Delivered lectures on Ethnicity and Nationalism',
      'Taught Anthropology of Poverty',
      'Examined and marked student assessments',
    ],
    skills: ['Anthropology', 'Ethnic Studies', 'Poverty Analysis'],
  },

  // ADMINISTRATIVE ROLES
  {
    id: 9,
    position: 'Coordinator of Examinations and Community Outreach',
    company: 'Catholic University of Eastern Africa',
    period: 'Jun 2016 - Apr 2020',
    location: 'Langata, Gaba and Kisumu Campuses',
    type: 'Administration',
    category: 'administration',
    description: 'Coordinated examinations and community service programmes for Faculty of Arts and Social Sciences.',
    responsibilities: [
      'Chaired Faculty committee for community service programmes',
      'Coordinated examination timetables and supervisor allocation',
      'Liaised with organizations for student field placements',
      'Generated supervision schedules for field attachments',
      'Collected and filed field reports and marks',
      'Resolved issues related to examinations and field attachments',
    ],
    skills: ['Examination Management', 'Community Engagement', 'Student Placement', 'Faculty Administration'],
  },
  {
    id: 10,
    position: 'Field Attachment and Internships Coordinator',
    company: 'Catholic University of Eastern Africa',
    period: 'Mar 2015 - Jun 2016',
    location: 'Langata and Kisumu, Kenya',
    type: 'Administration',
    category: 'administration',
    description: 'Coordinated field attachments and internships for Social Sciences and Development Studies departments.',
    responsibilities: [
      'Contacted and liaised with organizations for student placements',
      'Generated supervision schedules and allocated field supervisors',
      'Collected field reports and filed marks',
      'Resolved issues related to field attachments',
    ],
    skills: ['Internship Coordination', 'Industry Liaison', 'Student Supervision', 'Placement Management'],
  },

  // CONSULTING ROLES
  {
    id: 11,
    position: 'Lead Consultant - Research on TOC',
    company: 'Lake Tanganyika Basin Project',
    period: 'Feb 2025 (Ongoing)',
    location: 'DRC Region',
    type: 'Consulting',
    category: 'consulting',
    description: 'Research on Transnational Organized Crime activity in the Lake Tanganyika basin.',
    responsibilities: [
      'Establish contacts with key stakeholders in border management',
      'Co-develop research instruments',
      'Conduct key informant interviews and focus group discussions',
      'Analyse data on transnational organised crimes typologies',
      'Co-author research report with team',
      'Participate in dissemination events',
    ],
    skills: ['Transnational Crime Research', 'Stakeholder Interviews', 'Focus Groups', 'Policy Recommendations'],
  },
  {
    id: 12,
    position: 'Technical Expert',
    company: 'Lamu County DRM Policy',
    period: 'Sep 2021',
    location: 'Lamu County, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Technical workshop for Lamu County Disaster Risk Management Policy and Legislation.',
    responsibilities: [
      'Review of Lamu County DRM bill',
      'Drafting DRM policy for Lamu county',
      'Drafting Implementation Framework',
    ],
    skills: ['Policy Development', 'Disaster Risk Management', 'Legal Framework', 'Multi-agency Collaboration'],
  },
  {
    id: 13,
    position: 'Lead Consultant',
    company: 'Strategic Planning - FABEC Civil Engineers',
    period: 'Jul 2016',
    location: 'Dar-es-Salaam, Tanzania',
    type: 'Consulting',
    category: 'consulting',
    description: 'Facilitation of Strategic Planning Workshop for FABEC Civil Engineers.',
    responsibilities: [
      'Coordinated team of three staff members',
      'Conducted SWOT and PESTLE Analysis',
      'Conducted risk analysis for strategic plan',
      'Prepared implementation matrix',
      'Wrote the strategic plan document',
    ],
    skills: ['Strategic Planning', 'SWOT Analysis', 'Risk Assessment', 'Workshop Facilitation'],
  },
  {
    id: 14,
    position: 'Lead Consultant',
    company: 'Conflict Assessment - NCCK',
    period: 'Oct - Nov 2015',
    location: 'Dadaab Refugee Camp, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Trend analysis on conflict assessment for National Council of Churches of Kenya.',
    responsibilities: [
      'Coordinated team of seven researchers',
      'Generated background and analytical information on conflicts',
      'Identified root causes and stakeholder perceptions',
      'Produced recommendations for conflict resolution approaches',
      'Identified linkages with existing peace building programs',
    ],
    skills: ['Conflict Analysis', 'Peace Building', 'Refugee Studies', 'Stakeholder Analysis'],
  },
  {
    id: 15,
    position: 'Associate Consultant',
    company: 'Service Charter - Kisii County',
    period: 'Feb - Jul 2015',
    location: 'Kisii County, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Development of Service Charter for Kisii County Government Finance and Economic Planning sector.',
    responsibilities: [
      'Conducted stakeholder meetings with sector staff',
      'Performed needs assessment from external customers',
      'Reviewed various documents including Customer Satisfaction Survey',
      'Compiled report to inform Service Charter',
      'Wrote and presented the Service Charter',
    ],
    skills: ['Service Design', 'Customer Satisfaction', 'Public Sector Consulting', 'Policy Implementation'],
  },
  {
    id: 16,
    position: 'Lead Consultant',
    company: 'Customer Satisfaction Survey - Kisii County',
    period: 'Nov - Dec 2014',
    location: 'Kisii County, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Customer Satisfaction Survey for Kisii County Government.',
    responsibilities: [
      'Carried out comprehensive customer satisfaction survey',
      'Developed recommendations based on field findings',
      'Enabled setting up of customer satisfaction coordination mechanism',
      'Provided experience for Service Charter development',
      'Strengthened county capacity for customer satisfaction strategy',
    ],
    skills: ['Survey Design', 'Customer Experience', 'Public Administration', 'Data-driven Recommendations'],
  },
  {
    id: 17,
    position: 'Associate Consultant',
    company: 'Strategic Planning - Kisii County',
    period: 'Jul - Aug 2014',
    location: 'Kisii County, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Strategic Planning for Sector of Finance and Economic Planning, Kisii County Government.',
    responsibilities: [
      'Conducted stakeholder analysis with locals, diaspora, employees',
      'Performed SWOT and PESTLE analysis',
      'Drafted four-year strategic plan for Finance Sector',
      'Developed implementation plan',
    ],
    skills: ['Strategic Management', 'Local Government', 'Economic Planning', 'Implementation Strategy'],
  },

  // EARLIER RESEARCH EXPERIENCE
  {
    id: 18,
    position: 'Team Leader, Data Collection',
    company: 'CRECHE & Kenya Play Network',
    period: 'May 2016',
    location: 'Kenya',
    type: 'Research',
    category: 'research',
    description: 'Led data collection exercise for child play rights research.',
    responsibilities: [
      'Mobilized and managed team of 31 students',
      'Trained enumerators on data collection',
      'Coordinated data collection using standardized interview guides',
      'Cleaned interview schedules post-collection',
      'Managed completion of 220 questionnaires',
    ],
    achievements: [
      'Successfully completed 220 questionnaires',
      'Data used for lobbying for child play rights policy',
    ],
    skills: ['Field Research', 'Team Leadership', 'Data Collection Management', 'Survey Administration'],
  },
  {
    id: 19,
    position: 'Research Volunteer',
    company: 'RUDESAT International',
    period: 'Jan 2008 - 2010',
    location: 'Nairobi, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Volunteer research assistant for rural development through technology appropriation.',
    responsibilities: [
      'Assisted in developing concepts for donor funding',
      'Participated in repackaging technologies for rural use',
      'Compiled and edited field reports for Executive Director',
      'Monitored technology uptake and collected user feedback',
      'Provided logistic support during workshops',
    ],
    skills: ['Rural Development', 'Technology Transfer', 'Report Writing', 'NGO Operations'],
  },
  {
    id: 20,
    position: 'PhD Researcher',
    company: 'Kenyatta University',
    period: 'Aug 2011 - Feb 2019',
    location: 'Busia County, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Doctoral research on Households and Group Networks in Fish Farming Development.',
    achievements: [
      'Completed PhD thesis successfully',
      'Published multiple papers from research findings',
    ],
    skills: ['Academic Research', 'Qualitative Analysis', 'Thesis Writing', 'Field Studies'],
  },
  {
    id: 21,
    position: 'Research Assistant',
    company: 'International Forestry Resources Institute',
    period: 'May 2006 - Apr 2007',
    location: 'Kakamega, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Research on factors affecting tree planting uptake by farmers.',
    responsibilities: [
      'Conducted research on tree planting efforts',
      'Compiled report on factors hampering farmer uptake',
      'Collaborated with Kenya Forestry Research Institute',
    ],
    skills: ['Forestry Research', 'Environmental Studies', 'Data Compilation', 'Academic Writing'],
  },

  // VOLUNTEER & INTERNSHIP
  {
    id: 22,
    position: 'Volunteer',
    company: 'Kenya Red Cross',
    period: 'Nov 2009',
    location: 'Nairobi, Kenya',
    type: 'Volunteer',
    category: 'administration',
    description: 'Logistical support for Kenya Red Cross/Red Crescent Meetings.',
    responsibilities: [
      'Facilitated delegates stay at hotel',
      'Received delegates and provided information packs',
      'Organized transport to and from meeting venue',
      'Addressed emergency situations concerning delegates',
      'Facilitated communication for French-speaking delegates',
    ],
    skills: ['Event Management', 'Logistics Coordination', 'Multilingual Support', 'Emergency Response'],
  },
  {
    id: 23,
    position: 'Intern',
    company: 'Kenya Forestry Research Institute',
    period: 'May 2006 - Jan 2007',
    location: 'Nairobi, Kenya',
    type: 'Internship',
    category: 'research',
    description: 'Intern in Social Forestry Division.',
    responsibilities: [
      'Participated in literature review and data collection',
      'Assisted in data cleaning, entry and analysis',
      'Contributed to report writing',
      'Trained community members on development aspects',
    ],
    skills: ['Research Assistance', 'Community Training', 'Data Management', 'Environmental Education'],
  },
];

// In the projects array - remove the "publications" category from the projects section
// Projects should only have: research, consulting, academic

export const projects = [
  {
    id: 1,
    title: 'Transnational Organized Crime in Lake Tanganyika',
    description: 'Comprehensive research on TOC activities and threats linked to lake use in the DRC region.',
    category: 'research',
    tech: ['Field Research', 'Stakeholder Analysis', 'Policy Recommendations', 'Focus Group Discussions'],
    stats: { Countries: 2, 'KIIs': 45, 'FGDs': 12 },
    github: null,
    demo: null,
  },
  {
    id: 2,
    title: 'Disaster Risk Reduction in Conflict Zones',
    description: 'Research focusing on food security in Lamu County to inform Kenya Defence Forces operations.',
    category: 'research',
    tech: ['GIS Mapping', 'Risk Assessment', 'Policy Analysis', 'Field Surveys'],
    stats: { Reports: 3, 'Workshops': 8, 'Policy Briefs': 5 },
    github: null,
    demo: null,
  },
  {
    id: 3,
    title: 'Lamu County DRM Policy Framework',
    description: 'Development of disaster risk management policy and legislation for Lamu County.',
    category: 'consulting',
    tech: ['Policy Development', 'Stakeholder Engagement', 'Legal Framework', 'Capacity Building'],
    stats: { 'Policy Docs': 3, 'Stakeholders': 25, 'Timeline': '3 months' },
    github: null,
    demo: null,
  },
  {
    id: 4,
    title: 'Strategic Planning - FABEC Engineers',
    description: 'Facilitation of strategic planning workshop for Tanzanian engineering firm.',
    category: 'consulting',
    tech: ['Strategic Planning', 'SWOT Analysis', 'Risk Assessment', 'Workshop Facilitation'],
    stats: { 'Workshops': 1, 'Team': 3, 'Outcome': '5-year Plan' },
    github: null,
    demo: null,
  },
  {
    id: 5,
    title: 'Conflict Assessment - Dadaab Refugee Camp',
    description: 'Trend analysis on conflict for NCCK peace building program over 12 years.',
    category: 'consulting',
    tech: ['Conflict Analysis', 'Peace Building', 'Refugee Studies', 'Qualitative Research'],
    stats: { 'Years': 12, 'Team': 7, 'Reports': 1 },
    github: null,
    demo: null,
  },
  {
    id: 6,
    title: 'PhD Research: Fish Farming in Busia County',
    description: 'Doctoral research on households and group networks in fish farming development.',
    category: 'academic',
    tech: ['Academic Research', 'Qualitative Analysis', 'Field Studies', 'Thesis Writing'],
    stats: { 'Duration': '8 years', 'Publications': 5, 'Field Sites': 15 },
    github: null,
    demo: null,
  },
];
// utils/constants.js - Update certificates array
export const certificates = [
  {
    id: 1,
    title: 'Doctor of Philosophy (Ph.D) in Sociology',
    issuer: 'Kenyatta University',
    date: 'February 2019',
    type: 'Doctorate',
    credentialId: 'KU-PHD-2019-001',
    imageUrl: '/images/certificates/phd.png', // Updated path
    altText: 'PhD Certificate from Kenyatta University'
  },
  {
    id: 2,
    title: 'Master of Arts in Sociology',
    issuer: 'University of Nairobi',
    date: '2009',
    type: 'Masters',
    credentialId: 'UON-MA-2009',
    imageUrl: '/images/certificates/masters.png', // Updated path
    altText: 'MA Certificate from University of Nairobi'
  },
  {
    id: 3,
    title: 'Bachelor of Arts in Social Sciences',
    issuer: 'Catholic University of Eastern Africa',
    date: '2007',
    type: 'Bachelors',
    credentialId: 'CUEA-BA-2007',
    imageUrl: '/images/certificates/bachelors.png', // Updated path
    altText: 'BA Certificate from Catholic University of Eastern Africa'
  },
  {
    id: 4,
    title: 'French Language Proficiency',
    issuer: 'Alliance Française',
    date: '2010',
    type: 'Language',
    credentialId: 'AF-C1-2010',
    // If you have a French certificate image, add it here:
    // imageUrl: '/images/certificates/french.png',
    altText: 'French Language Certificate'
  },
  {
    id: 5,
    title: 'SPSS Statistical Package',
    issuer: 'Intraglobal Training Institute',
    date: '2011',
    type: 'Technical',
    credentialId: 'ITI-SPSS-2011',
    // If you have an SPSS certificate image, add it here:
    // imageUrl: '/images/certificates/spss.png',
    altText: 'SPSS Statistical Package Certificate'
  },
];

export const publications = [
  {
    id: 1,
    title: 'Disaster Risk Reduction in Conflict Zones: Focus on Food Security in Lamu County, Kenya',
    authors: 'Michael Sitawa, Japheth Mwasaru',
    year: '2022',
    journal: 'International Peace Support Training Centre',
    type: 'Research Paper',
    keywords: ['Disaster Risk', 'Conflict', 'Food Security', 'Kenya'],
    abstract: 'This paper examines the intersection of disaster risk reduction and conflict in Lamu County...',
    link: '#',
  },
  {
    id: 2,
    title: 'Status of Persons with Disabilities in Maritime Disaster Risk Reduction',
    authors: 'Michael Sitawa, Mohamed Idriss',
    year: '2021',
    journal: 'Africa Amani Journal',
    type: 'Journal Article',
    keywords: ['Disability', 'Maritime Security', 'Inclusion'],
    abstract: 'Analysis of disability inclusion in maritime disaster risk reduction efforts...',
    link: 'https://www.researchgate.net/publication/352191678_Disability_Mainstreaming_in_Maritime_Disaster_Risk_Reduction_A_Case_of_Mombasa_and_Lamu_Counties_Kenya',
  },
  {
    id: 3,
    title: 'Multi-Stakeholder Engagement In Developing National Cyber Security',
    authors: 'Chepkoech, J., and Sitawa M.',
    year: '2023',
    journal: 'National Defence University-Kenya Journal',
    type: 'Journal Article',
    keywords: ['Cyber Security', 'Multi-stakeholder', 'Kenya Defence Forces'],
    abstract: 'Case study of multi-stakeholder engagement in cyber security development...',
    link: '#',
  },
  {
    id: 4,
    title: 'Climate Change and Conflict in the Horn of Africa: A Gendered Perspective',
    authors: 'Ali Jihan, Mwasigwa R and Sitawa Michael',
    year: '2022',
    journal: 'Africa Amani Journal',
    type: 'Journal Article',
    keywords: ['Climate Change', 'Conflict', 'Gender', 'Horn of Africa'],
    abstract: 'Gendered analysis of climate change and conflict interactions in the Horn of Africa...',
    link: '#',
  },
];

export const contactInfo = [
  {
    type: 'email',
    label: 'Email',
    value: 'michael.sitawa@gmail.com',
    href: 'mailto:michael.sitawa@gmail.com',
  },
  {
    type: 'phone',
    label: 'Phone',
    value: '+254 720 776 277',
    href: 'tel:+254720776277',
  },
  {
    type: 'location',
    label: 'Location',
    value: 'Nairobi, Kenya',
    href: 'https://maps.google.com/?q=Nairobi+Kenya',
  },
];

export const socialLinks = [
  { name: 'LinkedIn', icon: Linkedin, url: 'https://linkedin.com/in/michael-sitawa-ph-d-521b90112/' },
  { name: 'Email', icon: Mail, url: 'mailto:michael.sitawa@gmail.com' },
];