import { 
  Globe, Users, BookOpen, Target, Award, Languages,
  FileText, BarChart, Map, Shield, Cpu, Database,
  GitBranch, Cloud, Server, Terminal, Lock, Code,
  Linkedin, Twitter, Github, Mail, Phone, MapPin,
  Calendar, Briefcase, ExternalLink, Download,
  GraduationCap, Building, Search, Brain, Mic,
  Book, PieChart, UserCheck, Settings
} from 'lucide-react';

export const navLinks = [
  { name: 'Home', href: '#home' },
  { name: 'About', href: '#about' },
  { name: 'Experience', href: '#experience' },
  { name: 'Education', href: '#education' },
  { name: 'Projects', href: '#projects' },
  { name: 'Publications', href: '#publications' },
  { name: 'Gallery', href: '#gallery' }, 
  { name: 'Contact', href: '#contact' },
];

export const heroData = {
  name: 'Dr. Michael Sitawa Mugah',
  title: 'Senior Researcher & Strategic Consultant',
  bio: 'Ph.D in Sociology with extensive experience in Security Sector Reform, Peace Operations, and Maritime Security in Eastern Africa.',
  stats: [
    { value: '18+', label: 'Years Experience' },
    { value: '70+', label: 'Research Projects' },
    { value: '40+', label: 'Publications' },
    { value: '200+', label: 'Students & Officials Trained' },
  ],
};

export const aboutData = {
  bio: 'Driven by a passion for strategic management, market surveillance, networking, resource mobilization, research and publication, I have extensive experience in strategic planning, negotiation, conflict resolution, management, research, monitoring and evaluation, data collection, data analysis, presentation, and report writing.',
  stats: [
    { value: 'Ph.D', label: 'Sociology, Kenyatta University' },
    { value: 'M.A', label: 'Community Development, UoN' },
    { value: 'B.A', label: 'Social Sciences, CUEA' },
  ],
  competencies: [
    'Strategic Planning',
    'Security Sector Reform',
    'Peace Operations',
    'Maritime Security',
    'Conflict Resolution',
    'Policy Development',
    'Research Methodology',
    'Capacity Building',
    'Data Analysis',
    'Public Speaking',
    'Defence Studies',
    'Leadership Training',
    'Military Education',
    'National Security',
  ],
  languages: [
    { name: 'English', level: 'Native', proficiency: 100 },
    { name: 'French', level: 'Fluent', proficiency: 90 },
    { name: 'Kiswahili', level: 'Native', proficiency: 100 },
    { name: 'Luhya', level: 'Fluent', proficiency: 90 },
    { name: 'Lingala', level: 'Intermediate', proficiency: 60 },
  ],
};

export const skills = [
  { name: 'Strategic Planning', level: 'Expert', icon: <Target /> },
  { name: 'Research Methodology', level: 'Expert', icon: <BookOpen /> },
  { name: 'Data Analysis (SPSS)', level: 'Expert', icon: <BarChart /> },
  { name: 'Policy Analysis', level: 'Expert', icon: <FileText /> },
  { name: 'Conflict Resolution', level: 'Expert', icon: <Shield /> },
  { name: 'Project Management', level: 'Expert', icon: <Users /> },
  { name: 'Public Speaking', level: 'Expert', icon: <Mic /> },
  { name: 'Academic Writing', level: 'Expert', icon: <Book /> },
  { name: 'Stakeholder Engagement', level: 'Expert', icon: <UserCheck /> },
  { name: 'Resource Mobilization', level: 'Advanced', icon: <Settings /> },
  { name: 'National Security Strategy', level: 'Expert', icon: <Shield /> },
  { name: 'Defence Studies', level: 'Expert', icon: <GraduationCap /> },
  { name: 'Leadership Training', level: 'Expert', icon: <Users /> },
  { name: 'Military Education', level: 'Expert', icon: <GraduationCap /> },
  { name: 'Workshop Facilitation', level: 'Expert', icon: <Mic /> },
  { name: 'Curriculum Development', level: 'Expert', icon: <Book /> },
];

export const experienceCategories = [
  { id: 'all', label: 'All Experience', icon: <Briefcase /> },
  { id: 'research', label: 'Research', icon: <Search /> },
  { id: 'academic', label: 'Academic', icon: <GraduationCap /> },
  { id: 'consulting', label: 'Consulting', icon: <Building /> },
  { id: 'administration', label: 'Administration', icon: <Settings /> },
  { id: 'training', label: 'Training', icon: <BookOpen /> },
];

export const experiences = [
  {
    id: 1,
    position: 'Research Consultant',
    company: 'Institute for Security Studies - Central Africa Observatory',
    period: 'Aug 2025 - Present',
    location: 'Central Africa Region',
    type: 'Research',
    category: 'research',
    description: 'Research on Organized Crime and Violence in Central Africa region and Lake Chad Basin.',
    responsibilities: [
      'Conduct desktop research on organized crime and violence',
      'Assist in mapping and analysing academic and policy literature',
      'Contribute to survey design for research projects',
      'Analyse research findings using appropriate methodologies',
      'Prepare research reports and presentations',
      'Participate in dissemination workshops and seminars',
    ],
    skills: ['Organized Crime Research', 'Policy Analysis', 'Regional Security', 'Report Writing'],
  },
  {
    id: 2,
    position: 'Researcher',
    company: 'Institute for Security Studies',
    period: 'Aug 2024 - Apr 2025',
    location: 'Nairobi, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Enhancing Civil Society Engagement in Security Sector Governance.',
    responsibilities: [
      'Conduct desktop research to gather and synthesise existing information',
      'Assist in mapping and analysing academic and policy literature for Security Sector Reform',
      'Contribute to survey design tailored to research project objectives',
      'Analyse research findings using appropriate methodologies',
      'Prepare research reports and presentations for stakeholders',
      'Participate in dissemination workshops and seminars',
    ],
    achievements: [
      'Mapping of civil society organizations in security sector governance space in Eastern Africa',
      'Mapping of key stakeholders for engagement in Nairobi',
      'Report writing for civil society organizations project covering Eastern African region',
      'Organized Kenya Stakeholder Engagements in Nairobi',
    ],
    skills: ['Security Sector Reform', 'Civil Society Engagement', 'Stakeholder Mapping', 'Report Writing'],
  },
  {
    id: 3,
    position: 'Applied Researcher',
    company: 'International Peace Support Training Centre',
    period: 'May 2020 - Present',
    location: 'Karen, Nairobi',
    type: 'Research',
    category: 'research',
    description: 'Conducting evidence-based research on gender, peace and security issues in Eastern Africa region.',
    responsibilities: [
      'Conduct demand-led, evidence-based policy-oriented research',
      'Analyse gendered nature of emerging conflict trends in Eastern Africa',
      'Provide inputs for training related to peace operations',
      'Develop and utilize appropriate research methodologies',
      'Prepare background notes, briefings, and speeches for Senior Management',
      'Lead high-profile research activities and support colleagues',
    ],
    achievements: [
      'Secured $54,000 USD funding for Children, Peace and Security research conference',
      'Established international collaborations with 8+ institutions through MoUs',
      'Published 5+ research papers and books',
      'Constituted international review board for Africa Amani Journal',
      'Designed and implemented Centre visibility strategy',
    ],
    projects: [
      'Disaster Risk Reduction in Conflict Zones',
      'SDG 5 in Maritime Security',
      'Multi-agency coordination in IED Threat Mitigation',
    ],
    skills: ['Peace Operations', 'Gender Analysis', 'Research Design', 'Fundraising', 'International Collaboration'],
  },
  {
    id: 4,
    position: 'Instructor & Research Fellow',
    company: 'National Defence College Kenya',
    period: '2020 - Present',
    location: 'Karen, Nairobi',
    type: 'Teaching & Research',
    category: 'academic',
    description: 'Teaching senior military officers in national security, strategy, and defence studies at Kenya\'s premier defence college.',
    responsibilities: [
      'Deliver lectures on national security strategy to senior defence officials',
      'Supervise research projects for military officers',
      'Develop case studies on regional security challenges',
      'Provide strategic analysis for defence decision-making',
      'Mentor senior military leadership on contemporary security issues',
      'Participate in course design and curriculum development',
    ],
    achievements: [
      'Enhanced strategic thinking capabilities of senior military leadership',
      'Contributed to national security policy development',
      'Developed innovative teaching methodologies for defence studies',
      'Supervised research on modern military challenges',
    ],
    skills: ['National Security', 'Defence Studies', 'Military Education', 'Strategic Analysis', 'Senior Leadership Training'],
  },
  {
    id: 5,
    position: 'Interim Programme Head',
    company: 'National Defence University-Kenya',
    period: 'Dec 2021 - Present',
    location: 'Karen, Nairobi',
    type: 'Academic Leadership',
    category: 'academic',
    description: 'Lead the Master of Arts Programme in National Security and Strategy.',
    responsibilities: [
      'Academic and administrative head of the MA programme',
      'Chair regular departmental meetings and ensure policy implementation',
      'Represent programme on appropriate college committees',
      'Maintain proper standards of teaching and research',
      'Submit departmental budgets, procurement plans, and annual reports',
      'Provide performance reviews of academic and non-academic staff',
    ],
    achievements: [
      'Drafted Student Recruitment, Resource Mobilization, Scholarship policies',
      'Enhanced programme coordination between College and University',
      'Improved academic and administrative standards',
    ],
    skills: ['Academic Leadership', 'Program Management', 'Quality Assurance', 'Strategic Planning', 'Policy Development'],
  },
  {
    id: 6,
    position: 'Provision of Instructional Assistance',
    company: 'Joint Command and Staff College',
    period: 'Jan 2021 - Present',
    location: 'Karen, Nairobi',
    type: 'Teaching',
    category: 'academic',
    description: 'Prepare and deliver lectures for Grade 3 Course Participants preparing for promotion.',
    responsibilities: [
      'Prepare lecture materials for promotion courses',
      'Deliver lectures on Conflict Resolution and Management in Africa',
      'Teach courses on Africa Peace and Security Architecture',
      'Instruct on United Nations Organization structures and operations',
    ],
    skills: ['Military Education', 'Curriculum Development', 'Adult Learning', 'Security Studies'],
  },
  {
    id: 7,
    position: 'Senior Lecturer',
    company: 'Catholic University of Eastern Africa',
    period: 'Jan 2010 - Apr 2021',
    location: 'Langata and Kisumu, Kenya',
    type: 'Teaching',
    category: 'academic',
    description: 'Lectured across multiple departments and supervised student research.',
    responsibilities: [
      'Coordinated examinations timetables for Social Sciences department',
      'Researched and prepared book lists for Masters programmes',
      'Supervised research concepts and projects by students',
      'Prepared and delivered lectures for undergraduate and graduate courses',
      'Examined, invigilated, and marked examinations',
      'Participated in departmental meetings and curriculum review',
    ],
    courses: [
      'Community Development',
      'Sociology of Development',
      'Research Methods',
      'Social Theory',
      'Human Rights',
      'Natural Resources Management',
    ],
    achievements: [
      'Supervised 50+ Masters and undergraduate theses',
      'Spearheaded Faculty curriculum review across five departments',
      'Wrote Diploma programmes for the department',
    ],
    skills: ['Curriculum Development', 'Thesis Supervision', 'Course Design', 'Academic Assessment', 'Departmental Leadership'],
  },
  {
    id: 8,
    position: 'Part-time Lecturer',
    company: 'Kisii University',
    period: 'Jan 2015 - Present',
    location: 'Nairobi Campus',
    type: 'Teaching',
    category: 'academic',
    description: 'Teach Masters courses in Development Studies, Public Administration, and International Relations.',
    responsibilities: [
      'Prepare lecture materials for Masters courses',
      'Deliver lectures on Change and Development',
      'Teach Public Administration in Kenya',
      'Instruct on Politics and Development of Newly Industrialized Countries',
      'Examine and mark student assessments',
    ],
    skills: ['Graduate Teaching', 'International Relations', 'Public Administration', 'Development Studies'],
  },
  {
    id: 9,
    position: 'Part-time Lecturer',
    company: 'Chuka University',
    period: 'Jan 2014 - Apr 2015',
    location: 'Chuka, Kenya',
    type: 'Teaching',
    category: 'academic',
    description: 'Taught undergraduate courses in Sociology and Social Work.',
    responsibilities: [
      'Prepared lecture materials for Sociology courses',
      'Delivered lectures on Social Policy, Research Methods, and Rural Sociology',
      'Taught courses on Correctional Services and Social Stratification',
      'Examined and marked student assessments',
    ],
    skills: ['Sociology Instruction', 'Social Work Education', 'Undergraduate Teaching'],
  },
  {
    id: 10,
    position: 'Part-time Lecturer',
    company: 'Maseno University',
    period: 'May - Aug 2012',
    location: 'Kisumu, Kenya',
    type: 'Teaching',
    category: 'academic',
    description: 'Taught courses on Ethnicity, Nationalism, and Anthropology of Poverty.',
    responsibilities: [
      'Prepared lecture materials for assigned courses',
      'Delivered lectures on Ethnicity and Nationalism',
      'Taught Anthropology of Poverty',
      'Examined and marked student assessments',
    ],
    skills: ['Anthropology', 'Ethnic Studies', 'Poverty Analysis'],
  },
  {
    id: 11,
    position: 'Leadership Training Facilitator',
    company: 'Plaza Beach Hotel, Mombasa',
    period: 'May 2018',
    location: 'Mombasa, Kenya',
    type: 'Training',
    category: 'training',
    description: 'Leadership and Management Skills training for Kenya Association of Records Managers and Archivists.',
    responsibilities: [
      'Delivered intensive leadership training programme',
      'Empowered participants with knowledge, skills and attitudes for successful records leadership',
      'Covered basic principles of leadership and management',
      'Facilitated practical leadership skill development',
    ],
    achievements: [
      'Trained records managers in effective leadership',
      'Enhanced leadership capabilities in library and records management',
      'Developed customized training materials',
    ],
    skills: ['Leadership Training', 'Professional Development', 'Workshop Facilitation', 'Records Management'],
  },
  {
    id: 12,
    position: 'Capacity Building Consultant',
    company: 'Jubbaland State of Somalia Parliamentary Committees',
    period: 'Mar 2017',
    location: 'Somalia',
    type: 'Consulting',
    category: 'consulting',
    description: 'Capacity building for parliamentary committees in Jubbaland State of Somalia.',
    responsibilities: [
      'Enlightened participants on parliamentary functions',
      'Outlined oversight roles and responsibilities',
      'Acquainted participants with legislative processes',
      'Exposed participants to parliamentary committee types and roles',
      'Promoted gender mainstreaming in Somali public sector',
    ],
    achievements: [
      'Enhanced parliamentary capacity in Somalia',
      'Promoted gender equality in political participation',
      'Exposed Somali parliamentarians to international best practices',
    ],
    skills: ['Capacity Building', 'Parliamentary Development', 'Gender Mainstreaming', 'Post-conflict Governance'],
  },
  {
    id: 13,
    position: 'Lead Consultant',
    company: 'Strategic Planning Workshop - FABEC Civil Engineers',
    period: 'Jul 2016',
    location: 'Dar-es-Salaam, Tanzania',
    type: 'Consulting',
    category: 'consulting',
    description: 'Facilitation of Strategic Planning Workshop for FABEC Civil Engineers.',
    responsibilities: [
      'Coordinated team of three staff members',
      'Conducted SWOT and PESTLE Analysis',
      'Conducted risk analysis for strategic plan',
      'Prepared implementation matrix',
      'Wrote the strategic plan document',
    ],
    skills: ['Strategic Planning', 'SWOT Analysis', 'Risk Assessment', 'Workshop Facilitation'],
  },
  {
    id: 14,
    position: 'Lead Consultant',
    company: 'Conflict Assessment - National Council of Churches of Kenya',
    period: 'Oct - Nov 2015',
    location: 'Dadaab Refugee Camp, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Trend analysis on conflict assessment for peace building work in Dadaab Refugee Camp.',
    responsibilities: [
      'Coordinated team of seven researchers',
      'Generated background and analytical information on conflicts',
      'Identified root causes and stakeholder perceptions',
      'Produced recommendations for conflict resolution approaches',
      'Identified linkages with existing peace building programs',
    ],
    skills: ['Conflict Analysis', 'Peace Building', 'Refugee Studies', 'Stakeholder Analysis'],
  },
  {
    id: 15,
    position: 'Associate Consultant',
    company: 'Service Charter - Kisii County Government',
    period: 'Feb - Jul 2015',
    location: 'Kisii County, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Development of Service Charter for Kisii County Government Finance and Economic Planning sector.',
    responsibilities: [
      'Conducted stakeholder meetings with sector staff',
      'Performed needs assessment from external customers',
      'Reviewed various documents including Customer Satisfaction Survey',
      'Compiled report to inform Service Charter',
      'Wrote and presented the Service Charter',
    ],
    skills: ['Service Design', 'Customer Satisfaction', 'Public Sector Consulting', 'Policy Implementation'],
  },
  {
    id: 16,
    position: 'Facilitator',
    company: 'Leadership and Management Skills Training',
    period: 'Apr 2015',
    location: 'Laico Regency Hotel, Nairobi',
    type: 'Training',
    category: 'training',
    description: 'Leadership and Management Skills training for professionals.',
    responsibilities: [
      'Conducted comprehensive leadership training',
      'Covered team development and conflict resolution',
      'Facilitated planning and productivity sessions',
      'Taught pressure management and delegation concepts',
    ],
    skills: ['Professional Training', 'Leadership Development', 'Team Building', 'Conflict Management'],
  },
  {
    id: 17,
    position: 'Lead Consultant',
    company: 'Customer Satisfaction Survey - Kisii County Government',
    period: 'Nov - Dec 2014',
    location: 'Kisii County, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Customer Satisfaction Survey for Kisii County Government.',
    responsibilities: [
      'Carried out comprehensive customer satisfaction survey',
      'Developed recommendations based on field findings',
      'Enabled setting up of customer satisfaction coordination mechanism',
      'Provided experience for Service Charter development',
      'Strengthened county capacity for customer satisfaction strategy',
    ],
    skills: ['Survey Design', 'Customer Experience', 'Public Administration', 'Data-driven Recommendations'],
  },
  {
    id: 18,
    position: 'Associate Consultant',
    company: 'Strategic Planning - Kisii County Government',
    period: 'Sep - Oct 2014 & Jul - Aug 2014',
    location: 'Kisii County, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Strategic Planning for various sectors of Kisii County Government.',
    responsibilities: [
      'Conducted stakeholder analysis with locals, diaspora, employees',
      'Performed SWOT and PESTLE analysis',
      'Drafted four-year strategic plans',
      'Developed implementation plans',
    ],
    skills: ['Strategic Management', 'Local Government', 'Economic Planning', 'Implementation Strategy'],
  },
  {
    id: 19,
    position: 'Coordinator of Examinations and Community Outreach',
    company: 'Catholic University of Eastern Africa',
    period: 'Jun 2016 - Apr 2020',
    location: 'Langata, Gaba and Kisumu Campuses',
    type: 'Administration',
    category: 'administration',
    description: 'Coordinated examinations and community service programmes for Faculty of Arts and Social Sciences.',
    responsibilities: [
      'Chaired Faculty committee for community service programmes',
      'Coordinated examination timetables and supervisor allocation',
      'Liaised with organizations for student field placements',
      'Generated supervision schedules for field attachments',
      'Collected and filed field reports and marks',
      'Resolved issues related to examinations and field attachments',
    ],
    skills: ['Examination Management', 'Community Engagement', 'Student Placement', 'Faculty Administration'],
  },
  {
    id: 20,
    position: 'Field Attachment and Internships Coordinator',
    company: 'Catholic University of Eastern Africa',
    period: 'Mar 2015 - Jun 2016',
    location: 'Langata and Kisumu, Kenya',
    type: 'Administration',
    category: 'administration',
    description: 'Coordinated field attachments and internships for Social Sciences and Development Studies departments.',
    responsibilities: [
      'Contacted and liaised with organizations for student placements',
      'Generated supervision schedules and allocated field supervisors',
      'Collected field reports and filed marks',
      'Resolved issues related to field attachments',
    ],
    skills: ['Internship Coordination', 'Industry Liaison', 'Student Supervision', 'Placement Management'],
  },
  {
    id: 21,
    position: 'Team Leader, Data Collection',
    company: 'CRECHE & Kenya Play Network',
    period: 'May 2016',
    location: 'Kenya',
    type: 'Research',
    category: 'research',
    description: 'Led data collection exercise for child play rights research.',
    responsibilities: [
      'Mobilized and managed team of 31 students',
      'Trained enumerators on data collection',
      'Coordinated data collection using standardized interview guides',
      'Cleaned interview schedules post-collection',
      'Managed completion of 220 questionnaires',
    ],
    achievements: [
      'Successfully completed 220 questionnaires',
      'Data used for lobbying for child play rights policy',
    ],
    skills: ['Field Research', 'Team Leadership', 'Data Collection Management', 'Survey Administration'],
  },
  {
    id: 22,
    position: 'Research Volunteer',
    company: 'RUDESAT International',
    period: 'Jan 2008 - 2010',
    location: 'Nairobi, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Volunteer research assistant for rural development through technology appropriation.',
    responsibilities: [
      'Assisted in developing concepts for donor funding',
      'Participated in repackaging technologies for rural use',
      'Compiled and edited field reports for Executive Director',
      'Monitored technology uptake and collected user feedback',
      'Provided logistic support during workshops',
    ],
    skills: ['Rural Development', 'Technology Transfer', 'Report Writing', 'NGO Operations'],
  },
  {
    id: 23,
    position: 'PhD Researcher',
    company: 'Kenyatta University',
    period: 'Aug 2011 - Feb 2019',
    location: 'Busia County, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Doctoral research on Households and Group Networks in Fish Farming Development.',
    achievements: [
      'Completed PhD thesis successfully',
      'Published multiple papers from research findings',
    ],
    skills: ['Academic Research', 'Qualitative Analysis', 'Thesis Writing', 'Field Studies'],
  },
  {
    id: 24,
    position: 'Research Assistant',
    company: 'University of Nairobi',
    period: '2009',
    location: 'Kiambu District, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Research on Farmers adoption of Tissue Culture Banana technologies.',
    responsibilities: [
      'Reviewed secondary data from agricultural research institutes',
      'Collected primary data using questionnaires and interviews',
      'Conducted focused group discussions with farmers groups',
      'Assessed adoption levels, performance and marketing',
      'Analyzed contribution to food security',
    ],
    skills: ['Agricultural Research', 'Technology Adoption', 'Food Security', 'Field Data Collection'],
  },
  {
    id: 25,
    position: 'Researcher',
    company: 'International Forestry Resources Institute',
    period: 'May 2006 - Apr 2007',
    location: 'Kakamega Forest, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Research on factors hampering tree planting efforts by farmers.',
    responsibilities: [
      'Conducted research on tree planting efforts',
      'Compiled report on factors hampering farmer uptake',
      'Collaborated with Kenya Forestry Research Institute',
      'Maintained database of forest cover in Kenya',
    ],
    skills: ['Forestry Research', 'Environmental Studies', 'Data Compilation', 'Academic Writing'],
  },
  {
    id: 26,
    position: 'Researcher',
    company: 'Catholic University of Eastern Africa',
    period: '2006 - 2007',
    location: 'Kikuyu Division, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Research on factors leading to alcohol consumption among youth.',
    responsibilities: [
      'Conducted review of secondary data',
      'Collected primary data from secondary schools',
      'Compiled comprehensive research report',
      'Analyzed socio-cultural factors influencing alcohol consumption',
    ],
    skills: ['Youth Studies', 'Substance Abuse Research', 'Educational Research', 'Data Analysis'],
  },
  {
    id: 27,
    position: 'Research Team Leader',
    company: 'Sustainable Agriculture & Natural Resources Management',
    period: 'Jul - Aug 2006',
    location: 'Kakamega Forest, Kenya',
    type: 'Research',
    category: 'research',
    description: 'Led data collection team investigating household dependency on Kakamega Forest.',
    responsibilities: [
      'Led data collection team in household survey',
      'Pre-tested questionnaires and mapped survey areas',
      'Managed time and budget allowances',
      'Gave daily progress reports to team',
      'Investigated household dependency levels on forest resources',
    ],
    skills: ['Team Leadership', 'Field Research Management', 'Questionnaire Design', 'Environmental Economics'],
  },
  {
    id: 28,
    position: 'Volunteer',
    company: 'Kenya Red Cross',
    period: 'Nov 2009',
    location: 'Nairobi, Kenya',
    type: 'Volunteer',
    category: 'training',
    description: 'Logistical support for Kenya Red Cross/Red Crescent Meetings.',
    responsibilities: [
      'Facilitated delegates stay at hotel',
      'Received delegates and provided information packs',
      'Organized transport to and from meeting venue',
      'Addressed emergency situations concerning delegates',
      'Facilitated communication for French-speaking delegates',
    ],
    skills: ['Event Management', 'Logistics Coordination', 'Multilingual Support', 'Emergency Response'],
  },
  {
    id: 29,
    position: 'Intern',
    company: 'Kenya Forestry Research Institute',
    period: 'May 2006 - Jan 2007',
    location: 'Nairobi, Kenya',
    type: 'Internship',
    category: 'research',
    description: 'Intern in Social Forestry Division.',
    responsibilities: [
      'Participated in literature review and data collection',
      'Assisted in data cleaning, entry and analysis',
      'Contributed to report writing',
      'Trained community members on development aspects',
    ],
    skills: ['Research Assistance', 'Community Training', 'Data Management', 'Environmental Education'],
  },
  {
    id: 30,
    position: 'Consultant',
    company: 'Association of Sisterhoods of Kenya',
    period: 'Apr - Jun 2020',
    location: 'Nairobi, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Drafting of Sustainable Child Rights Protection and Care Programme manual.',
    responsibilities: [
      'Developed national model for trainers of trainees',
      'Created comprehensive child rights protection manual',
      'Designed sustainable care programme framework',
      'Developed training materials for religious sisters',
    ],
    skills: ['Child Rights Protection', 'Programme Development', 'Training Manuals', 'Religious Organizations'],
  },
  {
    id: 31,
    position: 'Technical Expert',
    company: 'Lamu County DRM Policy',
    period: 'Sep 2021',
    location: 'Lamu County, Kenya',
    type: 'Consulting',
    category: 'consulting',
    description: 'Technical workshop for Lamu County Disaster Risk Management Policy and Legislation.',
    responsibilities: [
      'Review of Lamu County DRM bill',
      'Drafting DRM policy for Lamu county',
      'Drafting Implementation Framework',
    ],
    skills: ['Disaster Risk Management', 'Policy Development', 'Legal Framework', 'Multi-agency Collaboration'],
  },
  {
    id: 32,
    position: 'Associate Consultant - Research on TOC',
    company: 'Lake Tanganyika Basin Project',
    period: 'Feb 2025 (Ongoing)',
    location: 'DRC Region',
    type: 'Consulting',
    category: 'consulting',
    description: 'Research on Transnational Organized Crime activity in the Lake Tanganyika basin.',
    responsibilities: [
      'Establish contacts with key stakeholders in border management',
      'Co-develop research instruments',
      'Conduct key informant interviews and focus group discussions',
      'Analyse data on transnational organised crimes typologies',
      'Co-author research report with team',
      'Participate in dissemination events',
    ],
    skills: ['Transnational Crime Research', 'Stakeholder Interviews', 'Focus Groups', 'Policy Recommendations'],
  },
   {
    id: 33,
    position: 'Research Consultant - East Africa Community Regional Force',
    company: 'Kenya Defence Forces Headquarters / EACRF',
    period: 'Jan 2025 - Apr 2025',
    location: 'Eastern Democratic Republic of Congo',
    type: 'Research & Deployment',
    category: 'research',
    description: 'Deployed as civilian research specialist on soft power doctrine and human security to support East Africa Community Regional Force mission.',
    responsibilities: [
      'Carried out research study on "Disaster Risk Reduction in Conflict Zones: Focus on Food Security in Eastern DRC"',
      'Presented periodic reports on research findings to mission leadership',
      'Provided regular briefs on community perceptions of EACRF mission progress',
      'Suggested recommendations to improve mission effectiveness and community engagement',
      'Applied soft power approaches in conflict stabilization efforts',
      'Conducted field assessments in humanitarian security contexts'
    ],
    achievements: [
      'Developed comprehensive research methodology for conflict zone assessment',
      'Enhanced mission understanding of local community dynamics',
      'Contributed to improved civil-military coordination strategies',
      'Provided evidence-based recommendations for mission adaptation'
    ],
    skills: [
      'Soft Power Doctrine',
      'Human Security',
      'Conflict Zone Research',
      'Civil-Military Coordination',
      'Humanitarian Security',
      'Field Assessment',
      'Community Perception Analysis',
      'Mission Effectiveness Evaluation'
    ],
  },

];

export const projects = [
  {
    id: 1,
    title: 'Transnational Organized Crime in Lake Tanganyika',
    description: 'Comprehensive research on TOC activities and threats linked to lake use in the DRC region.',
    category: 'research',
    tech: ['Field Research', 'Stakeholder Analysis', 'Policy Recommendations', 'Focus Group Discussions'],
    stats: { Countries: 2, 'KIIs': 45, 'FGDs': 12 },
    github: null,
    demo: null,
  },
  {
    id: 2,
    title: 'Disaster Risk Reduction in Conflict Zones',
    description: 'Research focusing on food security in Lamu County to inform Kenya Defence Forces operations.',
    category: 'research',
    tech: ['GIS Mapping', 'Risk Assessment', 'Policy Analysis', 'Field Surveys'],
    stats: { Reports: 3, 'Workshops': 8, 'Policy Briefs': 5 },
    github: null,
    demo: null,
  },
  {
    id: 3,
    title: 'Lamu County DRM Policy Framework',
    description: 'Development of disaster risk management policy and legislation for Lamu County.',
    category: 'consulting',
    tech: ['Policy Development', 'Stakeholder Engagement', 'Legal Framework', 'Capacity Building'],
    stats: { 'Policy Docs': 3, 'Stakeholders': 25, 'Timeline': '3 months' },
    github: null,
    demo: null,
  },
  {
    id: 4,
    title: 'Strategic Planning - FABEC Engineers',
    description: 'Facilitation of strategic planning workshop for Tanzanian engineering firm.',
    category: 'consulting',
    tech: ['Strategic Planning', 'SWOT Analysis', 'Risk Assessment', 'Workshop Facilitation'],
    stats: { 'Workshops': 1, 'Team': 3, 'Outcome': '5-year Plan' },
    github: null,
    demo: null,
  },
  {
    id: 5,
    title: 'Conflict Assessment - Dadaab Refugee Camp',
    description: 'Trend analysis on conflict for NCCK peace building program over 12 years.',
    category: 'consulting',
    tech: ['Conflict Analysis', 'Peace Building', 'Refugee Studies', 'Qualitative Research'],
    stats: { 'Years': 12, 'Team': 7, 'Reports': 1 },
    github: null,
    demo: null,
  },
  {
    id: 6,
    title: 'PhD Research: Fish Farming in Busia County',
    description: 'Doctoral research on households and group networks in fish farming development.',
    category: 'academic',
    tech: ['Academic Research', 'Qualitative Analysis', 'Field Studies', 'Thesis Writing'],
    stats: { 'Duration': '8 years', 'Publications': 5, 'Field Sites': 15 },
    github: null,
    demo: null,
  },
  {
    id: 7,
    title: 'Leadership Training Programme',
    description: 'Comprehensive leadership training for records managers and archivists.',
    category: 'training',
    tech: ['Leadership Development', 'Workshop Design', 'Professional Training', 'Skill Assessment'],
    stats: { 'Participants': 200, 'Duration': '2 days', 'Modules': 8 },
    github: null,
    demo: null,
  },
  {
    id: 8,
    title: 'Capacity Building for Somali Parliament',
    description: 'Strengthening parliamentary committees in Jubbaland State of Somalia.',
    category: 'consulting',
    tech: ['Parliamentary Development', 'Governance', 'Capacity Building', 'Gender Mainstreaming'],
    stats: { 'Committees': 5, 'Duration': '1 week', 'Participants': 50 },
    github: null,
    demo: null,
  },
];

export const education = [
  {
    id: 1,
    degree: 'Doctor of Philosophy (Ph.D) in Sociology',
    institution: 'Kenyatta University',
    period: 'Feb 2019',
    location: 'Nairobi, Kenya',
    description: 'Doctoral research focused on households and group networks in fish farming development in Busia County.',
    highlights: ['Graduated with distinction', 'Published multiple papers', 'Presented at international conferences'],
    thesis: 'Households and Group Networks in Fish Farming Development: The Case of Busia County, Kenya',
  },
  {
    id: 2,
    degree: 'Master of Arts in Sociology',
    institution: 'University of Nairobi',
    period: '2009',
    location: 'Nairobi, Kenya',
    description: 'Specialized in community development and social research methodologies.',
    highlights: ['Distinction in research methodology', 'Community development focus', 'Policy analysis training'],
  },
  {
    id: 3,
    degree: 'Bachelor of Arts in Social Sciences',
    institution: 'Catholic University of Eastern Africa',
    period: '2007',
    location: 'Nairobi, Kenya',
    description: 'Double major in Sociology and Development Studies with minor in Philosophy.',
    highlights: ['First Class Honors', 'Student leader', 'Research assistant roles'],
  },
];

export const certificates = [
  {
    id: 1,
    title: 'Doctor of Philosophy (Ph.D) in Sociology',
    issuer: 'Kenyatta University',
    date: 'February 2019',
    type: 'Doctorate',
    credentialId: 'KU-PHD-2019-001',
    imageUrl: '/images/certificates/phd.png',
    altText: 'PhD Certificate from Kenyatta University'
  },
  {
    id: 2,
    title: 'Master of Arts in Sociology',
    issuer: 'University of Nairobi',
    date: '2009',
    type: 'Masters',
    credentialId: 'UON-MA-2009',
    imageUrl: '/images/certificates/masters.png',
    altText: 'MA Certificate from University of Nairobi'
  },
   {
    id: 3,
    title: 'Bachelor of Arts in Social Sciences',
    issuer: 'Catholic University of Eastern Africa',
    date: '2007',
    type: 'Bachelors',
    credentialId: 'CUEA-BA-2007',
    imageUrl: '/images/certificates/bachelors.png',
    altText: 'BA Certificate from Catholic University of Eastern Africa'
  },
   {
    id: 4,
    title: 'Rights and Protection of Children in Situations of Armed Conflict',
    issuer: 'École de Maintien de la Paix « Alioune Blondin BESYE »',
    date: 'May 2023',
    type: 'Professional Training',
    credentialId: 'EMP-ABB-2023',
    imageUrl: '/images/certificates/EMP.png',
    altText: 'Certificate on Rights and Protection of Children in Situations of Armed Conflict'
  },
 
  {
    id: 5,
    title: 'French Language Proficiency',
    issuer: 'Alliance Française',
    date: '2010',
    type: 'Language',
    credentialId: 'AF-C1-2010',
    altText: 'French Language Certificate'
  },
  {
    id: 6,
    title: 'SPSS Statistical Package',
    issuer: 'Intraglobal Training Institute',
    date: '2011',
    type: 'Technical',
    credentialId: 'ITI-SPSS-2011',
    altText: 'SPSS Statistical Package Certificate'
  },
  {
  id: 7,
  title: 'Certificate of Participation - Red Cross/Red Crescent General Assembly',
  issuer: 'International Federation of Red Cross and Red Crescent Societies',
  date: 'November 2009',
  type: 'International Training',
  credentialId: 'IFRC-GA-2009',
  imageUrl: '/images/certificates/red-cross.jpeg', // Make sure to add this image to your public/images/certificates folder
  altText: 'Red Cross/Red Crescent General Assembly Certificate 2009'
}
 
];

export const publications = [
  // Blog Articles
  {
    id: 1,
    title: 'The Jubaland Forces incursion: Safeguarding Kenya\'s territorial integrity amid regional volatility',
    authors: 'Michael Sitawa',
    year: '2024',
    journal: 'DefenceWeb',
    type: 'Blog Article',
    keywords: ['Jubaland', 'Kenya', 'Territorial Integrity', 'Regional Security', 'Border Security'],
    abstract: 'Analysis of Jubaland forces incursion and its implications for Kenya\'s territorial integrity in volatile regional context.',
    link: 'https://defenceweb.co.za/security/border-security/the-jubaland-forces-incursion-safeguarding-kenyas-territorial-integrity-amid-regional-volatility/',
  },
  {
    id: 2,
    title: 'Should Washington and Doha bankroll an EAC-SADC peace deployment in the DRC?',
    authors: 'Michael Sitawa',
    year: '2024',
    journal: 'DefenceWeb',
    type: 'Blog Article',
    keywords: ['DRC', 'Peace Deployment', 'EAC', 'SADC', 'International Funding'],
    abstract: 'Examination of potential US and Qatari funding for EAC-SADC peace deployment in Democratic Republic of Congo.',
    link: 'https://defenceweb.co.za/joint/diplomacy-a-peace/should-washington-and-doha-bankroll-an-eac-sade-peace-deployment-in-the-drc/',
  },
  {
    id: 3,
    title: 'Civil society remains the untapped link in improvised explosive device threat mitigation',
    authors: 'Sitawa M.',
    year: '2024',
    journal: 'DefenceWeb',
    type: 'Blog Article',
    keywords: ['Civil Society', 'IED', 'Threat Mitigation', 'Community Engagement', 'Security'],
    abstract: 'Discussion on the role of civil society organizations in improvised explosive device threat mitigation efforts.',
    link: 'https://defenceweb.co.za/african-news/civil-society-remains-the-untapped-link-in-improvised-explosive-device-threat-mitigation/',
  },
  {
    id: 4,
    title: 'Investment in the Blue Economy for enhanced Maritime Security',
    authors: 'Sitawa M.',
    year: '2022',
    journal: 'PRIF BLOG',
    type: 'Blog Article',
    keywords: ['Blue Economy', 'Maritime Security', 'Investment', 'Economic Development', 'Security'],
    abstract: 'Analysis of how investment in blue economy sectors can enhance maritime security in coastal regions.',
    link: 'https://blog.prif.org/2022/01/20/investment-in-the-blue-economy-for-enhanced-maritime-security/',
  },

  // Journal Articles - Published
  {
    id: 5,
    title: 'The status of the Namibian Defence Force capabilities in securing the maritime domain: a case of the Extended Continental Shelf',
    authors: 'Michael Sitawa',
    year: '2023',
    journal: 'HORN Bulletin',
    type: 'Journal Article',
    keywords: ['Namibia', 'Defence Force', 'Maritime Security', 'Continental Shelf', 'Capabilities'],
    abstract: 'Assessment of Namibian Defence Force capabilities in securing maritime domain and extended continental shelf.',
    link: 'https://horninstitute.org/wp-content/uploads/2024/03/HORN-Bulletin-Vol-VI-%E2%80%A2-Iss-VI-%E2%80%A2-November-December-2023.pdf',
  },
  {
    id: 6,
    title: 'Multi-Stakeholder Engagement In Developing National Cyber Security To Enhance National Development: Case Study of the Kenya Defence Forces',
    authors: 'Chepkoech, J., and Sitawa M.',
    year: '2023',
    journal: 'National Defence University-Kenya Journal',
    type: 'Journal Article',
    keywords: ['Cyber Security', 'Multi-stakeholder Engagement', 'Kenya Defence Forces', 'National Development'],
    abstract: 'Case study examining multi-stakeholder engagement in developing national cyber security capacity through Kenya Defence Forces.',
    link: 'https://journal.ndu.ac.ke/index.php/nsj/article/view/41',
  },
  {
    id: 7,
    title: 'State Craft through Effective Deployment of Peace Support Operations in Eastern Africa',
    authors: 'Sitawa M, Obwogi C. & Ogaye Martin',
    year: '2022',
    journal: 'Global Centre for Policy and Strategy Conference',
    type: 'Conference Paper',
    keywords: ['State Craft', 'Peace Support Operations', 'Eastern Africa', 'Security', 'Governance'],
    abstract: 'Analysis of statecraft approaches through deployment of peace support operations in Eastern African context.',
    link: '#',
  },
  {
    id: 8,
    title: 'Protection of Civilians in A Protracted Intra-State Armed Conflict: A Case of The Central African Republic (CAR)',
    authors: 'Watson Karuma, Martin Ogaye, Catherine Kirongothi, Michael Sitawa (PhD)',
    year: '2023',
    journal: 'Africa Amani Journal',
    type: 'Journal Article',
    keywords: ['Protection of Civilians', 'CAR', 'Armed Conflict', 'Peace Operations', 'Human Security'],
    abstract: 'Case study examining protection of civilians in protracted intra-state armed conflict in Central African Republic.',
    link: 'https://aaj.ipstc.org/wp-content/uploads/2023/07/Protection-of-Civilians-in-A-Protracted-Intra-State-Armed-Conflict-A-Case-of-The-Central-African-Republic-1.pdf',
  },
  {
    id: 9,
    title: 'Climate Change and Conflict in the Horn of Africa: A Gendered Perspective',
    authors: 'Ali Jihan, Mwasigwa R and Sitawa Michael',
    year: '2022',
    journal: 'Africa Amani Journal',
    type: 'Journal Article',
    keywords: ['Climate Change', 'Conflict', 'Gender', 'Horn of Africa', 'Security'],
    abstract: 'Gendered analysis of climate change-conflict nexus in the Horn of Africa region.',
    link: 'https://aaj.ipstc.org/wp-content/uploads/2022/10/Climate-Change-and-Conflict-in-the-Horn-of-Africa-A-Gendered-Perspective.pdf',
  },
  {
    id: 10,
    title: 'Status of Persons with Disabilities in maritime disaster risk reduction: A case of Mombasa and Lamu Counties, Kenya',
    authors: 'Sitawa M and Idriss M.',
    year: '2021',
    journal: 'Africa Amani Journal',
    type: 'Journal Article',
    keywords: ['Disability', 'Maritime Security', 'Disaster Risk Reduction', 'Inclusion', 'Kenya'],
    abstract: 'Assessment of disability inclusion in maritime disaster risk reduction efforts in coastal Kenya.',
    link: 'https://aaj.ipstc.org/wp-content/uploads/2021/04/Disability-Mainstreaming-in-Maritime-Disaster-Risk-Reduction-A-Case-of-Mombasa-and-Lamu-Counties-Kenya.pdf',
  },
  {
    id: 11,
    title: 'The Perceived benefits of Fish Farming to Rural Communities: The Demotivating Factors of The Sector\'s Development in Busia County, Kenya',
    authors: 'Mugah Michael Sitawa',
    year: '2018',
    journal: 'Beyond Borders: Advances in Global Welfare',
    type: 'Journal Article',
    keywords: ['Fish Farming', 'Rural Development', 'Busia County', 'Agriculture', 'Kenya'],
    abstract: 'Analysis of perceived benefits and demotivating factors in fish farming sector development in Busia County.',
    link: 'https://ejournals.bc.edu/index.php/bbagw/article/view/13049/10245',
  },
  {
    id: 12,
    title: 'Family Support and the Development of Fish Farming in Busia County',
    authors: 'Mugah Michael Sitawa, Dickson Ombaka and Parvin Moloo',
    year: '2018',
    journal: 'Journal of Research Innovation and Implications in Education (JRIIE)',
    type: 'Journal Article',
    keywords: ['Family Support', 'Fish Farming', 'Agricultural Development', 'Busia County', 'Rural Economy'],
    abstract: 'Examination of family support systems in fish farming development in Busia County, Kenya.',
    link: 'https://iritejournal.com/family-support-and-the-development-of-fish-farming-in-busia-county/',
  },
  {
    id: 13,
    title: 'Child Upbringing and Family Stability In Blended Households. A Case of Gihosha Commune, Bujumbura Province, Burundi',
    authors: 'Carine Irankunda, Shem Mwalwa and Michael Sitawa',
    year: '2018',
    journal: 'International Journal of Social Sciences',
    type: 'Journal Article',
    keywords: ['Child Upbringing', 'Family Stability', 'Blended Households', 'Burundi', 'Social Work'],
    abstract: 'Case study of child upbringing and family stability in blended households in Burundi.',
    link: 'http://www.iisdc.org/journal/show/child-upbringing-family-stability-blended-households-case-gihosha-bujumbura-burundi',
  },
  {
    id: 14,
    title: 'An evaluation of the effects of chewing Khat \'Muguka\' among the Youth in Kenya: A case study of Kapomboi Ward, Trans-Nzoia County',
    authors: 'Purity Nekesa Tabu, Urbanus Ndolo, Michael Sitawa',
    year: '2018',
    journal: 'International Journal of Social Sciences',
    type: 'Journal Article',
    keywords: ['Khat', 'Muguka', 'Youth', 'Substance Use', 'Kenya'],
    abstract: 'Evaluation of effects of khat chewing among youth in Trans-Nzoia County, Kenya.',
    link: 'http://www.ijsdc.org/journal/show/evaluation-effects-chewing-muguka-youth-kenya-kapomboiward-trans-nzoia',
  },
  {
    id: 15,
    title: 'Mineral exploitation and social economic growth in Goma Municipality, North Kivu, DR Congo',
    authors: 'Akonkwa Kalire Nadege, Dr. Urbanus Mwinzi Ndolo and Michael Sitawa Mugah',
    year: '2018',
    journal: 'International Journal of Social Sciences',
    type: 'Journal Article',
    keywords: ['Mineral Exploitation', 'Economic Growth', 'DR Congo', 'Mining', 'Development'],
    abstract: 'Analysis of mineral exploitation impacts on socio-economic growth in Goma, DRC.',
    link: 'http://www.ijsdc.org/journal/show/mineral-exploitation-social-economic-growth-goma-munincipality-north-kivu-congo',
  },
  {
    id: 16,
    title: 'Group networking and the development of fish farming in Busia County, Kenya',
    authors: 'Mugah Michael Sitawa, Dickson Ombaka and Parvin Moloo',
    year: '2018',
    journal: 'International Journal of Social Sciences',
    type: 'Journal Article',
    keywords: ['Group Networking', 'Fish Farming', 'Agricultural Development', 'Social Capital', 'Kenya'],
    abstract: 'Examination of group networking in fish farming development in Busia County.',
    link: 'http://www.ijsdc.org/journal/show/group-networking-and-the-development-of-fish-farming-in-busia-county-kenya',
  },
  {
    id: 17,
    title: 'Palliative care and the well-being of chronically ill inmates in Eldoret Prison Uasin-Gishu County, Kenya',
    authors: 'Faith Kimutai, Johnson Mavole and Michael Sitawa Mugah',
    year: '2018',
    journal: 'International Journal of Social Sciences',
    type: 'Journal Article',
    keywords: ['Palliative Care', 'Prison Health', 'Inmates', 'Well-being', 'Kenya'],
    abstract: 'Study of palliative care services for chronically ill inmates in Kenyan prison.',
    link: 'http://www.ijsdc.org/journal/show/palliative-care-and-the-well-being-of-chronically-ill%20inmates-in-eldoret-prison-uasin-gishu-county-kenya',
  },
  {
    id: 18,
    title: 'Challenges facing medical social work practice in Goma Provincial Hospital, Democratic Republic of Congo (DRC)',
    authors: 'Luzolo Matobo Sandra, Urbanus Mwinzi Ndolo and Michael Sitawa Mugah',
    year: '2018',
    journal: 'International Journal of Social Sciences',
    type: 'Journal Article',
    keywords: ['Medical Social Work', 'Healthcare', 'DR Congo', 'Challenges', 'Practice'],
    abstract: 'Analysis of challenges in medical social work practice in Goma, DRC.',
    link: 'http://www.ijsdc.org/journal/show/challenges-facing-medical-social-work-practice-in-goma-provincial-hospital-democratic-republi-of-congo-(drc)',
  },
  {
    id: 19,
    title: 'Influence of early marriage on the care of infants among adolescent mothers in Kiserian Sub-County, Kenya',
    authors: 'Marangu Timothy, Rev. Prof. Richard Rwiza, Michael Sitawa Mugah',
    year: '2017',
    journal: 'International Journal of Social Sciences',
    type: 'Journal Article',
    keywords: ['Early Marriage', 'Adolescent Mothers', 'Infant Care', 'Kenya', 'Maternal Health'],
    abstract: 'Study of early marriage impacts on infant care among adolescent mothers.',
    link: 'http://www.ijsdc.org/storage/[Vh8YhsHOyJ8l8ahdJNFuJoYz2y8ypN8qYtlf8dm.pdf',
  },
  {
    id: 20,
    title: 'Socio-economic factors affecting food security in rural households of Bukoba district-Tanzania',
    authors: 'Mavole Johnson (PhD), Michael Sitawa and Stella Bukuru',
    year: '2016',
    journal: 'International Journal of Social Sciences',
    type: 'Journal Article',
    keywords: ['Food Security', 'Socio-economic Factors', 'Tanzania', 'Rural Development', 'Agriculture'],
    abstract: 'Analysis of socio-economic factors affecting food security in rural Tanzania.',
    link: 'https://docs.google.com/viewer?a=v&pid=sites&srcid=ZGVmYXVsdGRvbWFpbnxzenNwZWt0cnVtfGd4OmFINjO1MjVhNTM3YjZjYg',
  },
  {
    id: 21,
    title: 'Social Dynamics influencing diabetes control: A case study of Vihiga district hospital',
    authors: 'Sitawa Michael and Carolyn Muhati',
    year: '2015',
    journal: 'International Journal of Social Sciences',
    type: 'Journal Article',
    keywords: ['Diabetes', 'Healthcare', 'Social Dynamics', 'Chronic Disease', 'Kenya'],
    abstract: 'Case study of social dynamics influencing diabetes control in Kenyan hospital.',
    link: 'http://www.ijsrit.com/uploaded_all_files/2790011991_a12.pdf',
  },
  {
    id: 22,
    title: 'The trends of skilled delivery among young parents in Lower Nyakach Division',
    authors: 'Sitawa Michael and Muchele Polycarp',
    year: '2013',
    journal: 'International Journal of Disaster Management and Risk Reduction',
    type: 'Journal Article',
    keywords: ['Skilled Delivery', 'Maternal Health', 'Young Parents', 'Healthcare', 'Kenya'],
    abstract: 'Study of skilled delivery trends among young parents in rural Kenya.',
    link: 'http://www.admerk.com/journal/paper_511.pdf',
  },
  {
    id: 23,
    title: 'The Role of biotechnology in improvement of food security and poverty reduction',
    authors: 'Sitawa Michael',
    year: '2012',
    journal: 'International Journal of Disaster Management and Risk Reduction',
    type: 'Journal Article',
    keywords: ['Biotechnology', 'Food Security', 'Poverty Reduction', 'Agriculture', 'Development'],
    abstract: 'Analysis of biotechnology role in food security and poverty reduction.',
    link: 'http://www.admerk.org/journal/',
  },

  // Papers Submitted (Awaiting Publication)
  {
    id: 24,
    title: 'Application of Research to Africa\'s Peace and Security Conundrum: The ethical and moral divide between the ideal and the real',
    authors: 'Sitawa M.',
    year: '2023',
    journal: 'Book Chapter (Submitted)',
    type: 'Book Chapter',
    keywords: ['Research Application', 'Peace and Security', 'Ethics', 'Africa', 'Policy'],
    abstract: 'Exploration of ethical and moral dimensions in applying research to Africa\'s peace and security challenges.',
    link: '#',
  },
  {
    id: 25,
    title: 'The effects of the fish industry on child education: A case study of Gwassi Beach, Homabay County',
    authors: 'Sitawa Michael and Manoti Sylvia',
    year: '2013',
    journal: 'Eastern Africa Journal of Humanities & Sciences (Submitted)',
    type: 'Journal Article',
    keywords: ['Fish Industry', 'Child Education', 'Fisheries', 'Education', 'Kenya'],
    abstract: 'Case study examining impacts of fish industry on child education in coastal Kenya.',
    link: '#',
  },
  {
    id: 26,
    title: 'The role of community mobilization and action in the fight against poverty in Kiambu District',
    authors: 'Sitawa Michael',
    year: '2011',
    journal: 'Eastern Africa Journal of Humanities & Sciences (Submitted)',
    type: 'Journal Article',
    keywords: ['Community Mobilization', 'Poverty Reduction', 'Development', 'Kiambu', 'Kenya'],
    abstract: 'Analysis of community mobilization role in poverty reduction efforts.',
    link: '#',
  },

  // Books and Book Chapters
  {
    id: 27,
    title: 'Child-upbringing and family stability in blended households',
    authors: 'Irankunda Carine and Sitawa Michael',
    year: '2018',
    journal: 'GRIN Verlag',
    type: 'Book',
    keywords: ['Child Upbringing', 'Family Stability', 'Blended Families', 'Parenting', 'Social Work'],
    abstract: 'Book examining child upbringing and family stability in blended household contexts.',
    link: 'https://www.grin.com/document/464113',
  },
  {
    id: 28,
    title: 'Community engagement and water program sustainability: Focus on Kitui Rural Sub-County, Kenya',
    authors: 'Michael Sitawa, Ransford Moore and Mavole J. (PhD)',
    year: '2018',
    journal: 'GRIN Verlag',
    type: 'Book',
    keywords: ['Community Engagement', 'Water Programs', 'Sustainability', 'Development', 'Kenya'],
    abstract: 'Study of community engagement in water program sustainability in rural Kenya.',
    link: 'https://www.grin.com/document/445368',
  },
  {
    id: 29,
    title: 'Challenges faced by youth engaging in agriculture. A study of peri urban Kiambu in Kenya',
    authors: 'Sitawa, M., Mugasia, E., & Songoro, A.',
    year: '2016',
    journal: 'GRIN Verlag',
    type: 'Book',
    keywords: ['Youth in Agriculture', 'Challenges', 'Peri-urban', 'Kenya', 'Rural Development'],
    abstract: 'Study of challenges facing youth engagement in agriculture in peri-urban Kenya.',
    link: 'https://www.grin.com/document/343332',
  },
  {
    id: 30,
    title: 'Disaster risk reduction in conflict zones: focus on food security in Lamu County, Kenya',
    authors: 'Sitawa M and Mwasaru, J.',
    year: '2022',
    journal: 'International Peace Support Training Centre',
    type: 'Research Monograph',
    keywords: ['Disaster Risk Reduction', 'Conflict Zones', 'Food Security', 'Lamu', 'Kenya'],
    abstract: 'Research on disaster risk reduction in conflict-affected areas with focus on food security.',
    link: '#',
  },
  {
    id: 31,
    title: 'Assessment of implementation of the United Nation\'s Sustainable Development Goal 5 in Kenya\'s Maritime Security Enforcement Sector',
    authors: 'Sitawa M and Mwachinalo D.',
    year: '2021',
    journal: 'International Peace Support Training Centre',
    type: 'Research Monograph',
    keywords: ['SDG 5', 'Gender Equality', 'Maritime Security', 'Kenya', 'Implementation'],
    abstract: 'Assessment of SDG 5 implementation in Kenya\'s maritime security sector.',
    link: '#',
  },
  {
    id: 32,
    title: 'Disability inclusion in maritime disaster risk reduction: A case of Mombasa and Lamu Counties, Kenya',
    authors: 'Sitawa M. and Idriss M. M.',
    year: '2020',
    journal: 'International Peace Support Training Centre',
    type: 'Research Monograph',
    keywords: ['Disability Inclusion', 'Maritime Security', 'Disaster Risk Reduction', 'Kenya'],
    abstract: 'Study of disability inclusion in maritime disaster risk reduction efforts.',
    link: '#',
  },
  {
    id: 33,
    title: 'Research Methodology Simplified',
    authors: 'Michael Sitawa and Dr. Hon. Lady Justice Scolastica Omondi (PhD)',
    year: '2023',
    journal: 'Law Africa',
    type: 'Book',
    keywords: ['Research Methodology', 'Academic Writing', 'Social Sciences', 'Guide'],
    abstract: 'Comprehensive guide to research methodology for social sciences.',
    link: '#',
  },

  // Book Chapters
  {
    id: 34,
    title: 'Deciphering the conflict and climate change conundrum in Lamu, Kenya: Application of the Sendai Framework to child protection',
    authors: 'Michael Sitawa (PhD) and Lieutenant Colonel Japheth Mwasaru',
    year: '2023',
    journal: 'Children, Peace and Security',
    type: 'Book Chapter',
    keywords: ['Climate Change', 'Conflict', 'Child Protection', 'Sendai Framework', 'Kenya'],
    abstract: 'Analysis of conflict-climate change nexus and child protection in Lamu, Kenya.',
    link: '#',
  },
  {
    id: 35,
    title: 'Politics and Development in Kenya, County by County',
    authors: 'Michael Sitawa (PhD) and Rickline Ng\'ayo and Maurice Amutabi (PhD)',
    year: '2023',
    journal: 'Taking Stock of Devolution in Kenya',
    type: 'Book Chapter',
    keywords: ['Politics', 'Development', 'Devolution', 'County Governance', 'Kenya'],
    abstract: 'Analysis of politics and development under Kenya\'s devolved system.',
    link: '#',
  },
  {
    id: 36,
    title: 'Poverty, Political Participation and Governance',
    authors: 'Michael Sitawa and Florence Ndamu',
    year: '2018',
    journal: 'Poverty Alleviation Strategies in East Africa',
    type: 'Book Chapter',
    keywords: ['Poverty', 'Political Participation', 'Governance', 'East Africa', 'Development'],
    abstract: 'Examination of poverty, political participation and governance linkages in East Africa.',
    link: '#',
  },

  // Additional Journal Articles from research section
  {
    id: 37,
    title: 'Multi-agency coordination in Improvised Explosive Device Threat Mitigation: Focus on Operation Amani Boni in Lamu County, Kenya',
    authors: 'Sitawa M, Mwasaru J and Ogaye M.',
    year: '2023',
    journal: 'International Peace Support Training Centre',
    type: 'Research Paper',
    keywords: ['IED', 'Multi-agency Coordination', 'Counter-terrorism', 'Lamu', 'Kenya'],
    abstract: 'Study of multi-agency coordination in IED threat mitigation in conflict-affected Lamu County.',
    link: '#',
  },

  // Conference Papers
  {
    id: 38,
    title: 'Mental health and Addictions: Remembering the \'Protector\' in Peace Operations',
    authors: 'Michael Sitawa',
    year: '2024',
    journal: 'Algoma University International Conference on Mental health and Addiction',
    type: 'Conference Paper',
    keywords: ['Mental Health', 'Peace Operations', 'Addiction', 'Peacekeepers', 'Well-being'],
    abstract: 'Examination of mental health and addiction issues among peacekeepers in operations.',
    link: '#',
  },
  {
    id: 39,
    title: 'BRICS and maritime security in the Western Indo-Pacific Region',
    authors: 'Michael Sitawa',
    year: '2023',
    journal: 'Symposium on Maritime Cooperation for African Security',
    type: 'Conference Paper',
    keywords: ['BRICS', 'Maritime Security', 'Indo-Pacific', 'International Relations', 'Security'],
    abstract: 'Analysis of BRICS role in maritime security in Western Indo-Pacific region.',
    link: '#',
  },
  {
    id: 40,
    title: 'State craft through Peace Operations in the face of Violent Extremism in Eastern Africa',
    authors: 'Michael Sitawa',
    year: '2023',
    journal: 'Regional Research Workshop',
    type: 'Conference Paper',
    keywords: ['State Craft', 'Peace Operations', 'Violent Extremism', 'Eastern Africa', 'Counter-terrorism'],
    abstract: 'Analysis of statecraft approaches through peace operations countering violent extremism.',
    link: '#',
  },
  {
    id: 41,
    title: 'Disaster Risk Reduction in Conflict Zones-Gaps in mental health interventions and drugs addictions',
    authors: 'Michael Sitawa',
    year: '2023',
    journal: 'Algoma University International Conference on Mental health and Addiction',
    type: 'Conference Paper',
    keywords: ['Disaster Risk Reduction', 'Mental Health', 'Addiction', 'Conflict Zones', 'Gaps'],
    abstract: 'Identification of gaps in mental health and addiction interventions in conflict zones.',
    link: '#',
  },
  {
    id: 42,
    title: 'The Kinetic vs soft power approaches in asymmetric theatres: Situating the balance for sustainable peace building in Lamu County, Kenya',
    authors: 'Michael Sitawa',
    year: '2022',
    journal: 'Peace Research Institute Frankfurt Conference',
    type: 'Conference Paper',
    keywords: ['Kinetic Power', 'Soft Power', 'Peace Building', 'Asymmetric Conflict', 'Kenya'],
    abstract: 'Analysis of kinetic vs soft power approaches in asymmetric conflict theaters for peace building.',
    link: '#',
  },
  {
    id: 43,
    title: 'Silencing the Guns: Remodelling Stabilization Efforts for "A Post-AMISOM" Somalia',
    authors: 'Michael Sitawa',
    year: '2021',
    journal: 'International Peace Support Training Centre Webinar',
    type: 'Conference Paper',
    keywords: ['Stabilization', 'AMISOM', 'Somalia', 'Peace Building', 'Security'],
    abstract: 'Analysis of stabilization efforts for post-AMISOM Somalia context.',
    link: '#',
  },
  {
    id: 44,
    title: 'Core Values of Rugby',
    authors: 'Michael Sitawa',
    year: '2021',
    journal: 'International Day Sports for Peace and Development',
    type: 'Conference Paper',
    keywords: ['Sports', 'Rugby', 'Peace Building', 'Values', 'Development'],
    abstract: 'Exploration of rugby core values and their application to peace and development.',
    link: '#',
  },
  {
    id: 45,
    title: 'Households and Group Networks in the Development of Fish Farming in Busia County, Kenya',
    authors: 'Michael Sitawa',
    year: '2019',
    journal: 'Kenyatta University PhD Graduands Seminar',
    type: 'Conference Paper',
    keywords: ['Fish Farming', 'Households', 'Group Networks', 'Agricultural Development', 'Kenya'],
    abstract: 'Presentation of PhD research findings on fish farming development in Busia County.',
    link: '#',
  },
  {
    id: 46,
    title: 'Ethics in Records Management',
    authors: 'Michael Sitawa',
    year: '2018',
    journal: 'Kenya Association of Records Managers and Archivists Conference',
    type: 'Conference Paper',
    keywords: ['Ethics', 'Records Management', 'Governance', 'Transparency', 'Accountability'],
    abstract: 'Discussion of ethical considerations in records management practices.',
    link: '#',
  },
  {
    id: 47,
    title: 'Women and the Post-Conflict Environment',
    authors: 'Michael Sitawa',
    year: '2015',
    journal: 'AMISOM Stabilization and Early Recovery Working Group',
    type: 'Conference Paper',
    keywords: ['Women', 'Post-conflict', 'Reconstruction', 'Gender', 'Peace Building'],
    abstract: 'Analysis of women\'s roles and challenges in post-conflict environments.',
    link: '#',
  },
  {
    id: 48,
    title: 'Cross-Sectoral partnerships for humanitarian aid and development assistance in a changing international context- A case of Somalia',
    authors: 'Michael Sitawa',
    year: '2015',
    journal: 'AMISOM Stabilization and Early Recovery Working Group',
    type: 'Conference Paper',
    keywords: ['Partnerships', 'Humanitarian Aid', 'Development', 'Somalia', 'Coordination'],
    abstract: 'Examination of cross-sectoral partnerships in humanitarian and development assistance.',
    link: '#',
  },
  {
    id: 49,
    title: 'Situating the Relevance of Information and Communication as a Dimension of Social Capital in Agricultural Development',
    authors: 'Michael Sitawa',
    year: '2015',
    journal: 'Catholic University of Eastern Africa Departmental Seminar',
    type: 'Conference Paper',
    keywords: ['Information', 'Communication', 'Social Capital', 'Agricultural Development', 'Technology'],
    abstract: 'Analysis of information and communication as social capital in agricultural development.',
    link: '#',
  },
  {
    id: 50,
    title: 'An Analysis of Media influence on family values in Sub-Saharan Africa',
    authors: 'Michael Sitawa',
    year: '2014',
    journal: 'Socio-Theological Conference',
    type: 'Conference Paper',
    keywords: ['Media', 'Family Values', 'Sub-Saharan Africa', 'Culture', 'Social Change'],
    abstract: 'Analysis of media influence on family values in African context.',
    link: '#',
  },
  {
    id: 51,
    title: 'The Social Capital Factor in agro-based Development',
    authors: 'Michael Sitawa',
    year: '2013',
    journal: 'International Interdisciplinary Conference',
    type: 'Conference Paper',
    keywords: ['Social Capital', 'Agricultural Development', 'Community', 'Networks', 'Development'],
    abstract: 'Examination of social capital role in agro-based development initiatives.',
    link: '#',
  },
];

export const contactInfo = [
  {
    type: 'email',
    label: 'Email',
    value: 'michael.sitawa@gmail.com',
    href: 'mailto:michael.sitawa@gmail.com',
  },
  {
    type: 'email',
    label: 'Institute Email',
    value: 'mmugah@issafrica.org',
    href: 'mailto:mmugah@issafrica.org',
  },
  {
    type: 'phone',
    label: 'Phone',
    value: '+254 720 776 277',
    href: 'tel:+254720776277',
  },
  {
    type: 'location',
    label: 'Location',
    value: 'Nairobi, Kenya',
    href: 'https://maps.google.com/?q=Nairobi+Kenya',
  },
];

export const socialLinks = [
  { name: 'LinkedIn', icon: Linkedin, url: 'https://linkedin.com/in/michael-sitawa-ph-d-521b90112/' },
  { name: 'Email', icon: Mail, url: 'mailto:michael.sitawa@gmail.com' },
];

export const professionalAssociations = [
  { name: 'African Studies Association', role: 'Member', since: 2015 },
  { name: 'International Studies Association', role: 'Member', since: 2018 },
  { name: 'Kenya Sociological Association', role: 'Member', since: 2010 },
  { name: 'Society for International Development', role: 'Member', since: 2012 },
  { name: 'Association of Disaster Management and Crisis Response-Kenya', role: 'Member', since: 2022 },
  { name: 'Kenya National Association of Social Workers', role: 'Member', since: 2019 },
];

export const languages = [
  { name: 'English', level: 'Native', proficiency: 100 },
  { name: 'French', level: 'Fluent', proficiency: 90 },
  { name: 'Kiswahili', level: 'Native', proficiency: 100 },
  { name: 'Luhya', level: 'Fluent', proficiency: 90 },
  { name: 'Lingala', level: 'Intermediate', proficiency: 60 },
];

export const awards = [
  {
    title: 'Best Research Paper Award',
    issuer: 'International Peace Support Training Centre',
    year: '2022',
    description: 'Awarded for outstanding research on disaster risk reduction in conflict zones'
  },
  {
    title: 'Excellence in Teaching Award',
    issuer: 'Catholic University of Eastern Africa',
    year: '2019',
    description: 'Recognized for outstanding teaching and student mentorship'
  },
  {
    title: 'Research Grant Award',
    issuer: 'African Peacebuilding Network',
    year: '2021',
    description: '$54,000 USD grant for Children, Peace and Security research conference'
  },
];

export const speakingTopics = [
  'Security Sector Reform in Eastern Africa',
  'Gender Mainstreaming in Peace Operations',
  'Maritime Security and Blue Economy',
  'Disaster Risk Reduction in Conflict Zones',
  'Youth Empowerment and Peacebuilding',
  'Academic Writing and Research Methodology',
  'Strategic Planning for Public Institutions',
  'Conflict Resolution and Mediation',
  'National Defence and Security Strategy',
  'Leadership Development in Military Contexts',
];

export const services = [
  {
    title: 'Research Services',
    description: 'Academic and policy-oriented research in security, development, and governance',
    icon: <Search />,
    deliverables: ['Research Papers', 'Policy Briefs', 'Literature Reviews', 'Data Analysis']
  },
  {
    title: 'Academic Services',
    description: 'Teaching, supervision, curriculum development, and academic leadership',
    icon: <GraduationCap />,
    deliverables: ['Course Development', 'Thesis Supervision', 'Lecturing', 'Academic Assessment']
  },
  {
    title: 'Consulting Services',
    description: 'Strategic planning, policy development, and institutional capacity building',
    icon: <Building />,
    deliverables: ['Strategic Plans', 'Policy Frameworks', 'Capacity Building', 'Workshop Facilitation']
  },
  {
    title: 'Training Services',
    description: 'Professional training in security studies, research methods, and leadership',
    icon: <BookOpen />,
    deliverables: ['Workshops', 'Training Modules', 'Custom Courses', 'Executive Education']
  },
  {
    title: 'Defence & Security Consulting',
    description: 'Expert advice on defence policy, security sector reform, and national security strategy',
    icon: <Shield />,
    deliverables: ['Defence Policy Review', 'Security Sector Assessment', 'National Security Strategy', 'Capacity Building']
  },
  {
    title: 'Executive Leadership Development',
    description: 'Senior leadership training and executive coaching for defence and security officials',
    icon: <Users />,
    deliverables: ['Executive Courses', 'Leadership Coaching', 'Strategic Planning Workshops', 'Senior Mentoring']
  },
];